# Generated by Django 4.2.1 on 2023-06-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='articles', to='blog.tag', verbose_name='Теги'),
        ),
    ]
